#!/usr/bin/env python3
"""Build a single-file uploadable XiangqiModelV2 engine."""

from __future__ import annotations

import ast
import pprint
from pathlib import Path

import numpy as np


ROOT = Path(__file__).resolve().parents[1]
SMARTPY_PATH = ROOT / "engines" / "smartpy_opt.py"
MODEL_PATH = ROOT / "models" / "xiangqi_model_v2.npz"
OUTPUT_PATH = ROOT / "engines" / "xiangqi_model_v2.py"


def _strip_shebang(source: str) -> str:
    if source.startswith("#!"):
        return source.split("\n", 1)[1]
    return source


def _strip_module_docstring(source: str) -> str:
    module = ast.parse(source)
    if not module.body:
        return source

    first = module.body[0]
    if not isinstance(first, ast.Expr):
        return source
    if not isinstance(first.value, ast.Constant):
        return source
    if not isinstance(first.value.value, str):
        return source

    lines = source.splitlines(keepends=True)
    del lines[first.lineno - 1 : first.end_lineno]
    while lines and not lines[0].strip():
        lines.pop(0)
    return "".join(lines)


def _load_smartpy_core() -> str:
    source = SMARTPY_PATH.read_text()
    source = _strip_shebang(source)
    source = _strip_module_docstring(source)

    marker = "\ndef main():\n"
    marker_index = source.index(marker)
    return source[:marker_index].rstrip() + "\n"


def build() -> None:
    smartpy_core = _load_smartpy_core()
    with np.load(MODEL_PATH) as data:
        model = {key: data[key].tolist() for key in data.files}

    output = f"""#!/usr/bin/env python3
\"\"\"XiangqiModelV2 - single-file upload build generated from SmartPy-Opt.\"\"\"

from __future__ import annotations

import sys

# Generated by scripts/build_xiangqi_model_v2.py. Do not edit manually.

{smartpy_core}

MODEL_EMB = {pprint.pformat(model["emb"], width=100)}
MODEL_LIN_W = {pprint.pformat(model["lin_w"], width=100)}
MODEL_HIDDEN_BIAS = {pprint.pformat(model["hidden_bias"], width=100)}
MODEL_LIN_TEMPO = {pprint.pformat(model["lin_tempo"], width=100)}
MODEL_TEMPO = {pprint.pformat(model["tempo"], width=100)}
MODEL_LIN_PHASE = {float(model["lin_phase"])}
MODEL_PHASE_VECTOR = {pprint.pformat(model["phase_vec"], width=100)}
MODEL_OUT_W = {pprint.pformat(model["out_w"], width=100)}
MODEL_OUT_BIAS = {float(model["out_bias"])}
MODEL_PHASE_OUT = {float(model["phase_out"])}
MODEL_ACT_CLIP = {float(model["act_clip"])}
MODEL_MAX_CORRECTION = {float(model["max_correction"])}
MODEL_PHASE_INV = {1.0 / 40.0}
MODEL_HIDDEN_SIZE = {len(model["hidden_bias"])}


class ModelBoard(Board):
    __slots__ = Board.__slots__ + ("acc", "lin_score")

    def __init__(self):
        super().__init__()
        self.acc = [0.0] * MODEL_HIDDEN_SIZE
        self.lin_score = 0.0

    def load_fen(self, fen):
        super().load_fen(fen)
        acc = self.acc
        self.lin_score = 0.0
        for i in range(MODEL_HIDDEN_SIZE):
            acc[i] = MODEL_HIDDEN_BIAS[i]
        for sq, piece in enumerate(self.sq):
            if not piece:
                continue
            self.lin_score += MODEL_LIN_W[piece + PIECE_OFFSET][sq]
            vec = MODEL_EMB[piece + PIECE_OFFSET][sq]
            for i in range(MODEL_HIDDEN_SIZE):
                acc[i] += vec[i]

    def make(self, move):
        fr = move // MOVE_STRIDE
        to = move - fr * MOVE_STRIDE
        piece = self.sq[fr]
        cap = self.sq[to]

        lin_from = MODEL_LIN_W[piece + PIECE_OFFSET][fr]
        lin_to = MODEL_LIN_W[piece + PIECE_OFFSET][to]
        cap_lin = MODEL_LIN_W[cap + PIECE_OFFSET][to] if cap else 0.0
        moved_from = MODEL_EMB[piece + PIECE_OFFSET][fr]
        moved_to = MODEL_EMB[piece + PIECE_OFFSET][to]
        cap_vec = MODEL_EMB[cap + PIECE_OFFSET][to] if cap else None

        cap = super().make(move)

        self.lin_score += lin_to - lin_from - cap_lin
        acc = self.acc
        for i in range(MODEL_HIDDEN_SIZE):
            acc[i] += moved_to[i] - moved_from[i]
            if cap_vec is not None:
                acc[i] -= cap_vec[i]
        return cap

    def undo(self, move, cap):
        fr = move // MOVE_STRIDE
        to = move - fr * MOVE_STRIDE
        piece = self.sq[to]

        lin_from = MODEL_LIN_W[piece + PIECE_OFFSET][fr]
        lin_to = MODEL_LIN_W[piece + PIECE_OFFSET][to]
        cap_lin = MODEL_LIN_W[cap + PIECE_OFFSET][to] if cap else 0.0
        moved_from = MODEL_EMB[piece + PIECE_OFFSET][fr]
        moved_to = MODEL_EMB[piece + PIECE_OFFSET][to]
        cap_vec = MODEL_EMB[cap + PIECE_OFFSET][to] if cap else None

        super().undo(move, cap)

        self.lin_score += lin_from - lin_to + cap_lin
        acc = self.acc
        for i in range(MODEL_HIDDEN_SIZE):
            acc[i] += moved_from[i] - moved_to[i]
            if cap_vec is not None:
                acc[i] += cap_vec[i]

    def eval(self):
        base = self.score if self.red_turn else -self.score
        phase = (self.red_phase + self.black_phase) * MODEL_PHASE_INV
        tempo = MODEL_TEMPO[0 if self.red_turn else 1]
        acc = self.acc

        corr = self.lin_score + MODEL_LIN_TEMPO[0 if self.red_turn else 1]
        corr += MODEL_OUT_BIAS + phase * (MODEL_LIN_PHASE + MODEL_PHASE_OUT)
        for i in range(MODEL_HIDDEN_SIZE):
            x = acc[i] + tempo[i] + phase * MODEL_PHASE_VECTOR[i]
            if x <= 0.0:
                continue
            if x > MODEL_ACT_CLIP:
                x = MODEL_ACT_CLIP
            corr += MODEL_OUT_W[i] * x

        if corr > MODEL_MAX_CORRECTION:
            corr = MODEL_MAX_CORRECTION
        elif corr < -MODEL_MAX_CORRECTION:
            corr = -MODEL_MAX_CORRECTION
        return int(round(base + corr))


class ModelEngine(Engine):
    def __init__(self):
        self.board = ModelBoard()
        self.board.load_fen(START_FEN)
        self.nodes = 0
        self.stop_time = 0.0
        self.start_time = 0.0
        self.stopped = False
        self.best_root = NO_MOVE
        self.history = [0] * (BOARD_SIZE * BOARD_SIZE)
        self.killers = [[NO_MOVE, NO_MOVE] for _ in range(MAX_PLY)]
        self.tt = {{}}

    def think(self, wtime, btime, winc, binc, movetime=None, max_depth=64):
        move = super().think(wtime, btime, winc, binc, movetime, max_depth)
        legal = self.board.gen_legal()
        if move in legal:
            return move
        return legal[0] if legal else NO_MOVE


def main():
    engine = ModelEngine()

    while True:
        try:
            line = input()
        except EOFError:
            break

        line = line.strip()
        if not line:
            continue

        if line == "uci":
            _out("id name XiangqiModelV2")
            _out("id author Codex")
            _out("id evalfile builtin-residual")
            _out("uciok")

        elif line == "isready":
            _out("readyok")

        elif line == "ucinewgame":
            engine.new_game()
            engine.board.load_fen(START_FEN)

        elif line.startswith("position"):
            tokens = line.split()
            if "fen" in tokens:
                idx = tokens.index("fen")
                end = tokens.index("moves") if "moves" in tokens else len(tokens)
                engine.board.load_fen(" ".join(tokens[idx + 1 : end]))
            elif "startpos" in tokens:
                engine.board.load_fen(START_FEN)
            if "moves" in tokens:
                idx = tokens.index("moves")
                for ms in tokens[idx + 1 :]:
                    engine.board.make(_uci2m(ms))

        elif line.startswith("go"):
            tokens = line.split()
            wtime = btime = 60000
            winc = binc = 0
            movetime = None
            depth = 64

            for i, token in enumerate(tokens):
                if token == "wtime":
                    wtime = int(tokens[i + 1])
                elif token == "btime":
                    btime = int(tokens[i + 1])
                elif token == "winc":
                    winc = int(tokens[i + 1])
                elif token == "binc":
                    binc = int(tokens[i + 1])
                elif token == "movetime":
                    movetime = int(tokens[i + 1])
                elif token == "depth":
                    depth = int(tokens[i + 1])

            best = engine.think(wtime, btime, winc, binc, movetime, depth)
            if best == NO_MOVE:
                moves = engine.board.gen_legal()
                best = moves[0] if moves else NO_MOVE
            _out(f"bestmove {{_m2uci(best)}}")

        elif line == "quit":
            break


if __name__ == "__main__":
    main()
"""

    OUTPUT_PATH.write_text(output)


if __name__ == "__main__":
    build()
