#!/usr/bin/env python3
"""Build a single-file uploadable XiangqiModelV4 engine."""

from __future__ import annotations

import pprint
import sys
from pathlib import Path

import numpy as np


ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

import scripts.build_xiangqi_model_v3 as base_build

MODEL_PATH = ROOT / "models" / "xiangqi_model_v4.npz"
OUTPUT_PATH = ROOT / "engines" / "xiangqi_model_v4.py"


def build() -> None:
    smartpy_core = base_build._load_smartpy_core()
    with np.load(MODEL_PATH) as data:
        model = {key: data[key].tolist() for key in data.files}

    output = f"""#!/usr/bin/env python3
\"\"\"XiangqiModelV4 - single-file upload build generated from SmartPy-Opt.\"\"\"

from __future__ import annotations

import sys

# Generated by scripts/build_xiangqi_model_v4.py. Do not edit manually.

{smartpy_core}

MODEL_EMB = {pprint.pformat(model["emb"], width=100)}
MODEL_LIN_W = {pprint.pformat(model["lin_w"], width=100)}
MODEL_RED_FAC = {pprint.pformat(model["red_fac"], width=100)}
MODEL_BLACK_FAC = {pprint.pformat(model["black_fac"], width=100)}
MODEL_HIDDEN_BIAS = {pprint.pformat(model["hidden_bias"], width=100)}
MODEL_LIN_TEMPO = {pprint.pformat(model["lin_tempo"], width=100)}
MODEL_TEMPO = {pprint.pformat(model["tempo"], width=100)}
MODEL_PHASE_VECTOR = {pprint.pformat(model["phase_vec"], width=100)}
MODEL_RED_KING_BIAS = {pprint.pformat(model["red_king_bias"], width=100)}
MODEL_BLACK_KING_BIAS = {pprint.pformat(model["black_king_bias"], width=100)}
MODEL_RED_KING_VEC = {pprint.pformat(model["red_king_vec"], width=100)}
MODEL_BLACK_KING_VEC = {pprint.pformat(model["black_king_vec"], width=100)}
MODEL_KING_PAIR_BIAS = {pprint.pformat(model["king_pair_bias"], width=100)}
MODEL_OUT_W = {pprint.pformat(model["out_w"], width=100)}
MODEL_OUT_BIAS = {float(model["out_bias"])}
MODEL_PHASE_OUT = {float(model["phase_out"])}
MODEL_ACT_CLIP = {float(model["act_clip"])}
MODEL_MAX_CORRECTION = {float(model["max_correction"])}
MODEL_PHASE_INV = {1.0 / 40.0}
MODEL_RED_BUCKET = {pprint.pformat(model["red_bucket"], width=100)}
MODEL_BLACK_BUCKET = {pprint.pformat(model["black_bucket"], width=100)}
MODEL_POLICY_PIECE = {pprint.pformat(model["policy_piece"], width=100)}
MODEL_POLICY_FROM = {pprint.pformat(model["policy_from"], width=100)}
MODEL_POLICY_TO = {pprint.pformat(model["policy_to"], width=100)}
MODEL_POLICY_CAPTURE = {pprint.pformat(model["policy_capture"], width=100)}
MODEL_NORM_BLACK = {pprint.pformat(model["norm_black"], width=100)}
MODEL_HIDDEN_SIZE = {len(model["hidden_bias"])}
MODEL_FACTOR_SIZE = {len(model["red_king_vec"][0])}


class ModelBoard(Board):
    __slots__ = Board.__slots__ + ("acc", "lin_score", "red_sum", "black_sum")

    def __init__(self):
        super().__init__()
        self.acc = [0.0] * MODEL_HIDDEN_SIZE
        self.lin_score = 0.0
        self.red_sum = [0.0] * MODEL_FACTOR_SIZE
        self.black_sum = [0.0] * MODEL_FACTOR_SIZE

    def load_fen(self, fen):
        super().load_fen(fen)
        acc = self.acc
        red_sum = self.red_sum
        black_sum = self.black_sum
        self.lin_score = 0.0
        for i in range(MODEL_HIDDEN_SIZE):
            acc[i] = MODEL_HIDDEN_BIAS[i]
        for i in range(MODEL_FACTOR_SIZE):
            red_sum[i] = 0.0
            black_sum[i] = 0.0
        for sq, piece in enumerate(self.sq):
            if not piece:
                continue
            plane = piece + PIECE_OFFSET
            self.lin_score += MODEL_LIN_W[plane][sq]
            vec = MODEL_EMB[plane][sq]
            red_vec = MODEL_RED_FAC[plane][sq]
            black_vec = MODEL_BLACK_FAC[plane][sq]
            for i in range(MODEL_HIDDEN_SIZE):
                acc[i] += vec[i]
            for i in range(MODEL_FACTOR_SIZE):
                red_sum[i] += red_vec[i]
                black_sum[i] += black_vec[i]

    def make(self, move):
        fr = move // MOVE_STRIDE
        to = move - fr * MOVE_STRIDE
        piece = self.sq[fr]
        cap = self.sq[to]
        plane = piece + PIECE_OFFSET

        lin_from = MODEL_LIN_W[plane][fr]
        lin_to = MODEL_LIN_W[plane][to]
        moved_from = MODEL_EMB[plane][fr]
        moved_to = MODEL_EMB[plane][to]
        red_from = MODEL_RED_FAC[plane][fr]
        red_to = MODEL_RED_FAC[plane][to]
        black_from = MODEL_BLACK_FAC[plane][fr]
        black_to = MODEL_BLACK_FAC[plane][to]

        cap_lin = 0.0
        cap_vec = None
        cap_red = None
        cap_black = None
        if cap:
            cap_plane = cap + PIECE_OFFSET
            cap_lin = MODEL_LIN_W[cap_plane][to]
            cap_vec = MODEL_EMB[cap_plane][to]
            cap_red = MODEL_RED_FAC[cap_plane][to]
            cap_black = MODEL_BLACK_FAC[cap_plane][to]

        cap = super().make(move)

        self.lin_score += lin_to - lin_from - cap_lin
        acc = self.acc
        red_sum = self.red_sum
        black_sum = self.black_sum
        for i in range(MODEL_HIDDEN_SIZE):
            acc[i] += moved_to[i] - moved_from[i]
            if cap_vec is not None:
                acc[i] -= cap_vec[i]
        for i in range(MODEL_FACTOR_SIZE):
            red_sum[i] += red_to[i] - red_from[i]
            black_sum[i] += black_to[i] - black_from[i]
            if cap_red is not None:
                red_sum[i] -= cap_red[i]
                black_sum[i] -= cap_black[i]
        return cap

    def undo(self, move, cap):
        fr = move // MOVE_STRIDE
        to = move - fr * MOVE_STRIDE
        piece = self.sq[to]
        plane = piece + PIECE_OFFSET

        lin_from = MODEL_LIN_W[plane][fr]
        lin_to = MODEL_LIN_W[plane][to]
        moved_from = MODEL_EMB[plane][fr]
        moved_to = MODEL_EMB[plane][to]
        red_from = MODEL_RED_FAC[plane][fr]
        red_to = MODEL_RED_FAC[plane][to]
        black_from = MODEL_BLACK_FAC[plane][fr]
        black_to = MODEL_BLACK_FAC[plane][to]

        cap_lin = 0.0
        cap_vec = None
        cap_red = None
        cap_black = None
        if cap:
            cap_plane = cap + PIECE_OFFSET
            cap_lin = MODEL_LIN_W[cap_plane][to]
            cap_vec = MODEL_EMB[cap_plane][to]
            cap_red = MODEL_RED_FAC[cap_plane][to]
            cap_black = MODEL_BLACK_FAC[cap_plane][to]

        super().undo(move, cap)

        self.lin_score += lin_from - lin_to + cap_lin
        acc = self.acc
        red_sum = self.red_sum
        black_sum = self.black_sum
        for i in range(MODEL_HIDDEN_SIZE):
            acc[i] += moved_from[i] - moved_to[i]
            if cap_vec is not None:
                acc[i] += cap_vec[i]
        for i in range(MODEL_FACTOR_SIZE):
            red_sum[i] += red_from[i] - red_to[i]
            black_sum[i] += black_from[i] - black_to[i]
            if cap_red is not None:
                red_sum[i] += cap_red[i]
                black_sum[i] += cap_black[i]

    def eval(self):
        base = self.score if self.red_turn else -self.score
        phase = (self.red_phase + self.black_phase) * MODEL_PHASE_INV
        side = 0 if self.red_turn else 1
        red_bucket = MODEL_RED_BUCKET[self.red_king] if self.red_king >= 0 else 4
        black_bucket = MODEL_BLACK_BUCKET[self.black_king] if self.black_king >= 0 else 4

        corr = self.lin_score + MODEL_LIN_TEMPO[side]
        corr += MODEL_OUT_BIAS + phase * MODEL_PHASE_OUT
        corr += MODEL_KING_PAIR_BIAS[red_bucket][black_bucket]

        acc = self.acc
        tempo = MODEL_TEMPO[side]
        red_bias = MODEL_RED_KING_BIAS[red_bucket]
        black_bias = MODEL_BLACK_KING_BIAS[black_bucket]
        for i in range(MODEL_HIDDEN_SIZE):
            x = acc[i] + tempo[i] + phase * MODEL_PHASE_VECTOR[i] + red_bias[i] + black_bias[i]
            if x <= 0.0:
                continue
            if x > MODEL_ACT_CLIP:
                x = MODEL_ACT_CLIP
            corr += MODEL_OUT_W[i] * x

        red_sum = self.red_sum
        black_sum = self.black_sum
        red_vec = MODEL_RED_KING_VEC[red_bucket]
        black_vec = MODEL_BLACK_KING_VEC[black_bucket]
        for i in range(MODEL_FACTOR_SIZE):
            corr += red_sum[i] * red_vec[i] + black_sum[i] * black_vec[i]

        if corr > MODEL_MAX_CORRECTION:
            corr = MODEL_MAX_CORRECTION
        elif corr < -MODEL_MAX_CORRECTION:
            corr = -MODEL_MAX_CORRECTION
        return int(round(base + corr))


class ModelEngine(Engine):
    def __init__(self):
        self.board = ModelBoard()
        self.board.load_fen(START_FEN)
        self.nodes = 0
        self.stop_time = 0.0
        self.start_time = 0.0
        self.stopped = False
        self.best_root = NO_MOVE
        self.history = [0] * (BOARD_SIZE * BOARD_SIZE)
        self.killers = [[NO_MOVE, NO_MOVE] for _ in range(MAX_PLY)]
        self.tt = {{}}

    def _policy_bucket(self):
        phase_total = self.board.red_phase + self.board.black_phase
        if phase_total >= 27:
            return 0
        if phase_total >= 14:
            return 1
        return 2

    def _policy_prior(self, move):
        fr = move // MOVE_STRIDE
        to = move - fr * MOVE_STRIDE
        piece = self.board.sq[fr]
        if not piece:
            return 0
        pt = piece if piece > 0 else -piece
        victim = self.board.sq[to]
        victim_pt = victim if victim > 0 else -victim
        if piece < 0:
            fr = MODEL_NORM_BLACK[fr]
            to = MODEL_NORM_BLACK[to]
        bucket = self._policy_bucket()
        return (
            MODEL_POLICY_PIECE[bucket][pt]
            + MODEL_POLICY_FROM[bucket][pt][fr]
            + MODEL_POLICY_TO[bucket][pt][to]
            + MODEL_POLICY_CAPTURE[bucket][victim_pt]
        )

    def _move_order(self, move, ply, tt_move):
        if move == tt_move:
            return 2_000_000
        to = move % MOVE_STRIDE
        cap = self.board.sq[to]
        prior = self._policy_prior(move)
        if cap:
            fr = move // MOVE_STRIDE
            attacker = self.board.sq[fr]
            return (
                1_000_000
                + MAT[cap if cap > 0 else -cap] * 16
                - MAT[attacker if attacker > 0 else -attacker]
                + prior // 12
            )
        killers = self.killers[ply]
        if move == killers[0]:
            return 900_000 + prior // 4
        if move == killers[1]:
            return 800_000 + prior // 4
        return self.history[move] + prior // 4

    def _order_captures(self, moves):
        board_sq = self.board.sq
        moves.sort(
            key=lambda move: (
                MAT[(board_sq[move % MOVE_STRIDE] if board_sq[move % MOVE_STRIDE] > 0 else -board_sq[move % MOVE_STRIDE])]
                * 16
                - MAT[(board_sq[move // MOVE_STRIDE] if board_sq[move // MOVE_STRIDE] > 0 else -board_sq[move // MOVE_STRIDE])]
            ),
            reverse=True,
        )
        return moves

    def think(self, wtime, btime, winc, binc, movetime=None, max_depth=64):
        move = super().think(wtime, btime, winc, binc, movetime, max_depth)
        legal = self.board.gen_legal()
        if move in legal:
            return move
        return legal[0] if legal else NO_MOVE


def main():
    engine = ModelEngine()

    while True:
        try:
            line = input()
        except EOFError:
            break

        line = line.strip()
        if not line:
            continue

        if line == "uci":
            _out("id name XiangqiModelV4")
            _out("id author Codex")
            _out("id evalfile builtin-residual-policy-v4")
            _out("uciok")

        elif line == "isready":
            _out("readyok")

        elif line == "ucinewgame":
            engine.new_game()
            engine.board.load_fen(START_FEN)

        elif line.startswith("position"):
            tokens = line.split()
            if "fen" in tokens:
                idx = tokens.index("fen")
                end = tokens.index("moves") if "moves" in tokens else len(tokens)
                engine.board.load_fen(" ".join(tokens[idx + 1 : end]))
            elif "startpos" in tokens:
                engine.board.load_fen(START_FEN)
            if "moves" in tokens:
                idx = tokens.index("moves")
                for ms in tokens[idx + 1 :]:
                    engine.board.make(_uci2m(ms))

        elif line.startswith("go"):
            tokens = line.split()
            wtime = btime = 60000
            winc = binc = 0
            movetime = None
            depth = 64

            for i, token in enumerate(tokens):
                if token == "wtime":
                    wtime = int(tokens[i + 1])
                elif token == "btime":
                    btime = int(tokens[i + 1])
                elif token == "winc":
                    winc = int(tokens[i + 1])
                elif token == "binc":
                    binc = int(tokens[i + 1])
                elif token == "movetime":
                    movetime = int(tokens[i + 1])
                elif token == "depth":
                    depth = int(tokens[i + 1])

            best = engine.think(wtime, btime, winc, binc, movetime, depth)
            if best == NO_MOVE:
                moves = engine.board.gen_legal()
                best = moves[0] if moves else NO_MOVE
            _out(f"bestmove {{_m2uci(best)}}")

        elif line == "quit":
            break


if __name__ == "__main__":
    main()
"""
    OUTPUT_PATH.write_text(output)


if __name__ == "__main__":
    build()
