#!/usr/bin/env python3
"""Build a single-file uploadable XiangqiModelV0 engine."""

from __future__ import annotations

import ast
import pprint
from pathlib import Path

import numpy as np


ROOT = Path(__file__).resolve().parents[1]
SMARTPY_PATH = ROOT / "engines" / "smartpy_opt.py"
MODEL_PATH = ROOT / "models" / "xiangqi_psqt_v0.npz"
OUTPUT_PATH = ROOT / "engines" / "xiangqi_model_v0.py"


def _strip_shebang(source: str) -> str:
    if source.startswith("#!"):
        return source.split("\n", 1)[1]
    return source


def _strip_module_docstring(source: str) -> str:
    module = ast.parse(source)
    if not module.body:
        return source

    first = module.body[0]
    if not isinstance(first, ast.Expr):
        return source
    if not isinstance(first.value, ast.Constant):
        return source
    if not isinstance(first.value.value, str):
        return source

    lines = source.splitlines(keepends=True)
    del lines[first.lineno - 1 : first.end_lineno]
    while lines and not lines[0].strip():
        lines.pop(0)
    return "".join(lines)


def _load_smartpy_core() -> str:
    source = SMARTPY_PATH.read_text()
    source = _strip_shebang(source)
    source = _strip_module_docstring(source)

    marker = "\ndef main():\n"
    marker_index = source.index(marker)
    return source[:marker_index].rstrip() + "\n"
def build() -> None:
    smartpy_core = _load_smartpy_core()
    with np.load(MODEL_PATH) as data:
        model_psq = data["psq"].tolist()
        model_bias = float(np.asarray(data["bias"]).item())
    model_psq_literal = pprint.pformat(model_psq, width=100)

    output = f"""#!/usr/bin/env python3
\"\"\"XiangqiModelV0 - single-file upload build generated from SmartPy-Opt.\"\"\"

from __future__ import annotations

import sys

# Generated by scripts/build_xiangqi_model_v0.py. Do not edit manually.

{smartpy_core}

PSQ = {model_psq_literal}
_MODEL_BIAS = {model_bias!r}


def main():
    def eval_model(self):
        score = self.score + _MODEL_BIAS
        score = score if self.red_turn else -score
        return int(round(score))

    Board.eval = eval_model
    engine = Engine()

    while True:
        try:
            line = input()
        except EOFError:
            break

        line = line.strip()
        if not line:
            continue

        if line == "uci":
            _out("id name XiangqiModelV0")
            _out("id author Codex")
            _out("id evalfile builtin")
            _out("uciok")

        elif line == "isready":
            _out("readyok")

        elif line == "ucinewgame":
            engine.new_game()
            engine.board.load_fen(START_FEN)

        elif line.startswith("position"):
            tokens = line.split()
            if "fen" in tokens:
                idx = tokens.index("fen")
                end = tokens.index("moves") if "moves" in tokens else len(tokens)
                engine.board.load_fen(" ".join(tokens[idx + 1 : end]))
            elif "startpos" in tokens:
                engine.board.load_fen(START_FEN)
            if "moves" in tokens:
                idx = tokens.index("moves")
                for ms in tokens[idx + 1 :]:
                    engine.board.make(_uci2m(ms))

        elif line.startswith("go"):
            tokens = line.split()
            wtime = btime = 60000
            winc = binc = 0
            movetime = None
            depth = 64

            for i, token in enumerate(tokens):
                if token == "wtime":
                    wtime = int(tokens[i + 1])
                elif token == "btime":
                    btime = int(tokens[i + 1])
                elif token == "winc":
                    winc = int(tokens[i + 1])
                elif token == "binc":
                    binc = int(tokens[i + 1])
                elif token == "movetime":
                    movetime = int(tokens[i + 1])
                elif token == "depth":
                    depth = int(tokens[i + 1])

            best = engine.think(wtime, btime, winc, binc, movetime, depth)
            if best == NO_MOVE:
                moves = engine.board.gen_legal()
                best = moves[0] if moves else NO_MOVE
            _out(f"bestmove {{_m2uci(best)}}")

        elif line == "quit":
            break


if __name__ == "__main__":
    main()
"""

    OUTPUT_PATH.write_text(output)


if __name__ == "__main__":
    build()
